services:
  postgres:
    image: postgres:16
    container_name: court_db
    restart: always
    environment:
      POSTGRES_USER: jonah
      POSTGRES_PASSWORD: jonah
      POSTGRES_DB: courtdb
    ports:
      - "65432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  scraper:
    build:
      context: ./whitechapel_advice_scraper
    env_file:
      - ./whitechapel_advice_scraper/.env
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./whitechapel_advice_scraper:/app


volumes:
  pgdata:

