-- insert all regions
INSERT INTO region (id,region_name)
VALUES
(1,'North West'),
(2,'North East'),
(3,'Midlands'),
(4,'Wales'),
(5,'Greater London'),
(6,'South West'),
(7,'South East');

-- insert all cities?
INSERT INTO city (city_name, region_id) VALUES
('Barrow in Furness', 1),
('Blackburn', 1),
('Blackpool', 1),
('Burnley', 1),
('Liverpool', 1),
('Manchester', 1),
('Preston', 1),
('St Helens', 1),
('Wigan', 1),
('Stockport', 1),
('Birkenhead', 1),
('Durham', 2),
('Gateshead', 2),
('Teesside (Middlesbrough)', 2),
('Newcastle Upon Tyne', 2),
('North Shields', 2),
('Sunderland', 2),
('Darlington', 2),
('West Cumbria', 2),
('Barnsley', 2),
('Birmingham', 3),
('Coventry', 3),
('Derby', 3),
('Leicester', 3),
('Lincoln', 3),
('Nottingham', 3),
('Stoke-on-Trent', 3),
('Wolverhampton', 3),
('Walsall', 3),
('Northampton', 3),
('Worcester', 3),
('Warwick', 3),
('Mansfield', 3),
('Nuneaton', 3),
('Cardiff', 4),
('Swansea', 4),
('Newport', 4),
('Llanelli', 4),
('Merthyr Tydfil', 4),
('Pontypridd', 4),
('Port Talbot', 4),
('Prestatyn', 4),
('Wrexham', 4),
('Caernarfon', 4),
('Haverfordwest', 4),
('Aberystwyth', 4),
('Barnet', 5),
('Brentford', 5),
('Bromley', 5),
('Central London', 5),
('Clerkenwell & Shoreditch', 5),
('Croydon', 5),
('East London', 5),
('Edmonton', 5),
('Romford', 5),
('Uxbridge', 5),
('Wandsworth', 5),
('West London Family', 5),
('Willesden', 5),
('Bath', 6),
('Bristol', 6),
('Exeter', 6),
('Gloucester', 6),
('Plymouth', 6),
('Taunton', 6),
('Torquay & Newton Abbot', 6),
('Truro', 6),
('Weston-Super-Mare', 6),
('Yeovil', 6),
('Aldershot & Farnham', 7),
('Basingstoke', 7),
('Brighton', 7),
('Canterbury', 7),
('Chelmsford', 7),
('Guildford', 7),
('Hastings', 7),
('High Wycombe', 7),
('Horsham', 7),
('Kingston upon Thames', 7),
('Maidstone', 7),
('Medway', 7),
('Oxford', 7),
('Portsmouth', 7),
('Reading', 7),
('Slough', 7),
('Southampton', 7),
('Southend', 7),
('Staines', 7),
('Thanet', 7),
('Watford', 7),
('Winchester', 7),
('Worthing', 7),
('Basildon', 7),
('Bedford', 7);
